name: 'lamblayer'
author: 'takahashi@adansons.co.jp'
description: 'A minimal deployment tool for AWS Lambda layers.'
inputs:
  version:
    description: "A version to install lamblayer"
    default: "v0.3.0"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - run: |
        cd /tmp
        curl -sL https://github.com/YU-SUKETAKAHASHI/lamblayer/archive/refs/tags/{{ inputs.version }}.tar.gz | tar zxvf -
        cd lamblayer-v{{ inputs.version }}
        pip install lamblayer
      shell: bashcd